baseURL = "https://raghurok.github.io/"
languageCode = "en-us"
title = "Raghu Ravi"
theme = "yinyang"
enableRobotsTXT = true
pygmentsUseClasses = true


[params.author]
  email = ""
  name = "Raghu Ravi"

[params]
  headTitle = "Raghu Ravi"
  mainSections = ["blogs"]
  favicon = "favicon.ico"
  images = []
  description = ""

[markup.goldmark.renderer]
  unsafe = true

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
